steps:
- name: gcr.io/cloud-builders/docker
  id: worker
  waitFor: ['-']
  entrypoint: bash
  args:
  - -c
  - "cp apps.json setup.py patch.py worker && docker build \
    --build-arg=BUILD_VERSION=$TAG_NAME \
    --build-arg=FRAPPE_VERSION=$_FRAPPE_VERSION \
    --build-arg=ERPNEXT_VERSION=$_ERPNEXT_VERSION \
    --build-arg=REGISTRY_PREFIX=$_REGISTRY_PREFIX \
    --tag=asia.gcr.io/$PROJECT_ID/erpnext-worker \
    worker"
- name: gcr.io/cloud-builders/docker
  waitFor: ['worker']
  args:
    - tag
    - asia.gcr.io/$PROJECT_ID/erpnext-worker
    - asia.gcr.io/$PROJECT_ID/erpnext-worker:$TAG_NAME
- name: gcr.io/cloud-builders/docker
  id: nginx
  waitFor: ['-']
  entrypoint: bash
  args:
  - -c
  - "cp apps.json setup.py patch.py nginx && docker build \
    --build-arg=BUILD_VERSION=$TAG_NAME \
    --build-arg=FRAPPE_VERSION=$_FRAPPE_VERSION \
    --build-arg=ERPNEXT_VERSION=$_ERPNEXT_VERSION \
    --build-arg=REGISTRY_PREFIX=$_REGISTRY_PREFIX \
    --tag=asia.gcr.io/$PROJECT_ID/erpnext-nginx \
    nginx"
- name: gcr.io/cloud-builders/docker
  waitFor: ['nginx']
  args:
    - tag
    - asia.gcr.io/$PROJECT_ID/erpnext-nginx
    - asia.gcr.io/$PROJECT_ID/erpnext-nginx:$TAG_NAME

substitutions:
  _FRAPPE_VERSION: v14.14.3
  _ERPNEXT_VERSION: v14.6.0
  _REGISTRY_PREFIX: frappe

timeout: 1800s
images:
- asia.gcr.io/$PROJECT_ID/erpnext-worker:$TAG_NAME
- asia.gcr.io/$PROJECT_ID/erpnext-worker:latest
- asia.gcr.io/$PROJECT_ID/erpnext-nginx:$TAG_NAME
- asia.gcr.io/$PROJECT_ID/erpnext-nginx:latest