version: "3.1"
services:
  mariadb:
    image: mariadb:10.3
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    volumes:
      - ./conf/maraidb/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf:ro
      - ./conf/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - $MYSQL_DATA:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    networks:
      - frappe_net

  redis-cache:
    image: redis:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./conf/redis/redis_cache.conf:/etc/conf.d/redis.conf:ro
    command: ["redis-server", "/etc/conf.d/redis.conf"]
    networks:
      - frappe_net

  redis-queue:
    image: redis:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./conf/redis/redis_queue.conf:/etc/conf.d/redis.conf:ro
    command: ["redis-server", "/etc/conf.d/redis.conf"]
    networks:
      - frappe_net

  redis-socketio:
    image: redis:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./conf/redis/redis_socketio.conf:/etc/conf.d/redis.conf:ro
    command: ["redis-server", "/etc/conf.d/redis.conf"]
    networks:
      - frappe_net

  frappe:
    build: ./
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    volumes:
      - ./conf/frappe:/home/frappe/conf:ro
      - $FRAPPE_BENCH:/home/frappe/frappe-bench
      - $LETSENCRYPT:/etc/letsencrypt
      - ./startup.sh:/home/frappe/startup.sh:ro
    ports:
      - "80:80"
      - "443:443"
    entrypoint: ["/tini", "--", "./startup.sh"]
    depends_on:
      - mariadb
      - redis-cache
      - redis-queue
      - redis-socketio
    networks:
      - frappe_net

networks:
  frappe_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
